// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportsComplexWebAPI.Data;

#nullable disable

namespace SportsComplexWebAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230902063439_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GymSection", b =>
                {
                    b.Property<int>("GymsId")
                        .HasColumnType("int");

                    b.Property<int>("SectionsId")
                        .HasColumnType("int");

                    b.HasKey("GymsId", "SectionsId");

                    b.HasIndex("SectionsId");

                    b.ToTable("GymSection");
                });

            modelBuilder.Entity("SportsComplexWebAPI.Models.Administrator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PassportNumber")
                        .HasColumnType("int");

                    b.Property<int>("PassportSeries")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Administrators");
                });

            modelBuilder.Entity("SportsComplexWebAPI.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("SportsComplexWebAPI.Models.ClientSeasonTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int?>("CoachId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<int>("GymId")
                        .HasColumnType("int");

                    b.Property<int>("SeasonTicketId")
                        .HasColumnType("int");

                    b.Property<int>("SectionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VisitsNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("CoachId");

                    b.HasIndex("GroupId");

                    b.HasIndex("GymId");

                    b.HasIndex("SeasonTicketId");

                    b.HasIndex("SectionId");

                    b.ToTable("ClientSeasonTickets");
                });

            modelBuilder.Entity("SportsComplexWebAPI.Models.ClientTraining", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientSeasonTicketId")
                        .HasColumnType("int");

                    b.Property<int>("TrainingId")
                        .HasColumnType("int");

                    b.Property<int>("Visiting")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientSeasonTicketId");

                    b.HasIndex("TrainingId");

                    b.ToTable("ClientTrainings");
                });

            modelBuilder.Entity("SportsComplexWebAPI.Models.Coach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PassportNumber")
                        .HasColumnType("int");

                    b.Property<int>("PassportSeries")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SectionId")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.ToTable("Coaches");
                });

            modelBuilder.Entity("SportsComplexWebAPI.Models.CoachContact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CoachId")
                        .HasColumnType("int");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CoachId");

                    b.ToTable("CoachContacts");
                });

            modelBuilder.Entity("SportsComplexWebAPI.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CoachId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CoachId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("SportsComplexWebAPI.Models.Gym", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Area")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Gyms");
                });

            modelBuilder.Entity("SportsComplexWebAPI.Models.SeasonTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AvailableVisits")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SeasonTickets");
                });

            modelBuilder.Entity("SportsComplexWebAPI.Models.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("SportsComplexWebAPI.Models.Training", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CoachId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Duration")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<int?>("GymId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SectionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CoachId");

                    b.HasIndex("GroupId");

                    b.HasIndex("GymId");

                    b.HasIndex("SectionId");

                    b.ToTable("Trainings");
                });

            modelBuilder.Entity("GymSection", b =>
                {
                    b.HasOne("SportsComplexWebAPI.Models.Gym", null)
                        .WithMany()
                        .HasForeignKey("GymsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportsComplexWebAPI.Models.Section", null)
                        .WithMany()
                        .HasForeignKey("SectionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SportsComplexWebAPI.Models.ClientSeasonTicket", b =>
                {
                    b.HasOne("SportsComplexWebAPI.Models.Client", "Client")
                        .WithMany("ClientSeasonTickets")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportsComplexWebAPI.Models.Coach", "Coach")
                        .WithMany("ClientSeasonTickets")
                        .HasForeignKey("CoachId");

                    b.HasOne("SportsComplexWebAPI.Models.Group", "Group")
                        .WithMany("ClientSeasonTickets")
                        .HasForeignKey("GroupId");

                    b.HasOne("SportsComplexWebAPI.Models.Gym", "Gym")
                        .WithMany()
                        .HasForeignKey("GymId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportsComplexWebAPI.Models.SeasonTicket", "SeasonTicket")
                        .WithMany("ClientSeasonTickets")
                        .HasForeignKey("SeasonTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportsComplexWebAPI.Models.Section", "Section")
                        .WithMany("ClientSeasonTickets")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Coach");

                    b.Navigation("Group");

                    b.Navigation("Gym");

                    b.Navigation("SeasonTicket");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("SportsComplexWebAPI.Models.ClientTraining", b =>
                {
                    b.HasOne("SportsComplexWebAPI.Models.ClientSeasonTicket", "ClientSeasonTicket")
                        .WithMany("ClientTrainings")
                        .HasForeignKey("ClientSeasonTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportsComplexWebAPI.Models.Training", "Training")
                        .WithMany("ClientTrainings")
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientSeasonTicket");

                    b.Navigation("Training");
                });

            modelBuilder.Entity("SportsComplexWebAPI.Models.Coach", b =>
                {
                    b.HasOne("SportsComplexWebAPI.Models.Section", "Section")
                        .WithMany("Coaches")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("SportsComplexWebAPI.Models.CoachContact", b =>
                {
                    b.HasOne("SportsComplexWebAPI.Models.Coach", "Coach")
                        .WithMany("CoachContacts")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("SportsComplexWebAPI.Models.Group", b =>
                {
                    b.HasOne("SportsComplexWebAPI.Models.Coach", "Coach")
                        .WithMany("Groups")
                        .HasForeignKey("CoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coach");
                });

            modelBuilder.Entity("SportsComplexWebAPI.Models.Training", b =>
                {
                    b.HasOne("SportsComplexWebAPI.Models.Coach", "Coach")
                        .WithMany("Trainings")
                        .HasForeignKey("CoachId");

                    b.HasOne("SportsComplexWebAPI.Models.Group", "Group")
                        .WithMany("Trainings")
                        .HasForeignKey("GroupId");

                    b.HasOne("SportsComplexWebAPI.Models.Gym", "Gym")
                        .WithMany("Trainings")
                        .HasForeignKey("GymId");

                    b.HasOne("SportsComplexWebAPI.Models.Section", "Section")
                        .WithMany("Trainings")
                        .HasForeignKey("SectionId");

                    b.Navigation("Coach");

                    b.Navigation("Group");

                    b.Navigation("Gym");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("SportsComplexWebAPI.Models.Client", b =>
                {
                    b.Navigation("ClientSeasonTickets");
                });

            modelBuilder.Entity("SportsComplexWebAPI.Models.ClientSeasonTicket", b =>
                {
                    b.Navigation("ClientTrainings");
                });

            modelBuilder.Entity("SportsComplexWebAPI.Models.Coach", b =>
                {
                    b.Navigation("ClientSeasonTickets");

                    b.Navigation("CoachContacts");

                    b.Navigation("Groups");

                    b.Navigation("Trainings");
                });

            modelBuilder.Entity("SportsComplexWebAPI.Models.Group", b =>
                {
                    b.Navigation("ClientSeasonTickets");

                    b.Navigation("Trainings");
                });

            modelBuilder.Entity("SportsComplexWebAPI.Models.Gym", b =>
                {
                    b.Navigation("Trainings");
                });

            modelBuilder.Entity("SportsComplexWebAPI.Models.SeasonTicket", b =>
                {
                    b.Navigation("ClientSeasonTickets");
                });

            modelBuilder.Entity("SportsComplexWebAPI.Models.Section", b =>
                {
                    b.Navigation("ClientSeasonTickets");

                    b.Navigation("Coaches");

                    b.Navigation("Trainings");
                });

            modelBuilder.Entity("SportsComplexWebAPI.Models.Training", b =>
                {
                    b.Navigation("ClientTrainings");
                });
#pragma warning restore 612, 618
        }
    }
}
